//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAndReplaceLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindAndReplaceLib.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?&lt;capturedGroup&gt;\$((?&lt;index&gt;\d+)|\{(?&lt;bracketedIndex&gt;\d+)\}|\{(?&lt;groupName&gt;\w+)\}))).
        /// </summary>
        internal static string rxCaptureGroupReplacement {
            get {
                return ResourceManager.GetString("rxCaptureGroupReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^(?&lt;filename&gt;[a-z0-9~\-_`!@#%=;, \{\}\(\)\&lt;\&gt;\^\&amp;\*\+\|\&quot;\&apos;\.\?]+)$).
        /// </summary>
        internal static string rxFilename {
            get {
                return ResourceManager.GetString("rxFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;namedGroup&gt;\$\{(?&lt;groupName&gt;\w+)\}).
        /// </summary>
        internal static string rxNamedGroupReplacement {
            get {
                return ResourceManager.GetString("rxNamedGroupReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^(?&lt;pathname&gt;[a-z0-9~\-_`!@#%=;, \{\}\(\)\&lt;\&gt;\^\&amp;\*\+\|\&quot;\&apos;\.\?\:\\/]+)$).
        /// </summary>
        internal static string rxPathName {
            get {
                return ResourceManager.GetString("rxPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^(\\\\|[a-z]{1}\:|[a-z]+\://|/)).
        /// </summary>
        internal static string rxPathStart {
            get {
                return ResourceManager.GetString("rxPathStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;functiontext&gt;(?&lt;functionname&gt;LoadFileContent)\((?&gt;\((?&lt;c&gt;)|(?&lt;parameters&gt;[^()]+)|\)(?&lt;-c&gt;))*(?(c)(?!))\))).
        /// </summary>
        internal static string rxReplacementStringFunctionLoadFileContent {
            get {
                return ResourceManager.GetString("rxReplacementStringFunctionLoadFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;functiontext&gt;(?&lt;functionname&gt;LowerCase)\((?&gt;\((?&lt;c&gt;)|(?&lt;parameters&gt;[^()]+)|\)(?&lt;-c&gt;))*(?(c)(?!))\))).
        /// </summary>
        internal static string rxReplacementStringFunctionLowerCase {
            get {
                return ResourceManager.GetString("rxReplacementStringFunctionLowerCase", resourceCulture);
            }
        }
    }
}
